// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipxmgyezyvrauyjsatet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlweG1neWV6eXZyYXV5anNhdGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTkwODgsImV4cCI6MjA2NTQ3NTA4OH0.wrN4Yod1jAa7hNLy-IzIz76hVzbJc5gjV-wquqEIbU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);